### ISSUE TITLE
regression: segmentation fault on rebuild with no inputs

### ISSUE THREAD

**Issue by bradking** [ninja-build/ninja#1290]
Changes in #1281 regressed this case:

```console
$ cat example.sh
rm -rf sub build.ninja .ninja_deps .ninja_log

echo '
subninja sub/build.ninja
default sub/out' > build.ninja

mkdir sub
echo '
rule touch
  command = touch $out
build sub/out: touch
' > sub/build.ninja

ninja
echo ---
ninja

$ sh example.sh
[1/1] touch sub/out
---
Segmentation fault
```

**Comment by colincross** [comment]
It's not subninja, its the rule with no inputs that triggers the segfault.

```
$ cat example.sh
rm -rf build.ninja .ninja_deps .ninja_log

echo '
rule touch
  command = touch $out
build out: touch
' > build.ninja

~/ssd/ninja/ninja
echo ---
~/ssd/ninja/ninja
```

```
Program received signal SIGSEGV, Segmentation fault.
DependencyScan::RecomputeOutputDirty (this=this@entry=0x7fffffffda00, edge=edge@entry=0x62ffc0, 
    most_recent_input=most_recent_input@entry=0x0, command="touch out", output=0x630280) at src/graph.cc:138
138	                                          Node* most_recent_input,
(gdb) bt
#0  DependencyScan::RecomputeOutputDirty (this=this@entry=0x7fffffffda00, edge=edge@entry=0x62ffc0, 
    most_recent_input=most_recent_input@entry=0x0, command="touch out", output=0x630280) at src/graph.cc:138
#1  0x0000000000415868 in DependencyScan::RecomputeOutputsDirty (this=this@entry=0x7fffffffda00, 
    edge=edge@entry=0x62ffc0, most_recent_input=most_recent_input@entry=0x0, 
    outputs_dirty=outputs_dirty@entry=0x7fffffffd7ff, err=err@entry=0x7fffffffd8b0) at src/graph.cc:129
#2  0x00000000004169e5 in DependencyScan::RecomputeDirty (this=this@entry=0x7fffffffda00, edge=edge@entry=0x62ffc0, 
    err=err@entry=0x7fffffffd8b0) at src/graph.cc:103
#3  0x000000000040bddb in Builder::AddTarget (this=this@entry=0x7fffffffd970, node=0x630280, 
    err=err@entry=0x7fffffffd8b0) at src/build.cc:644
#4  0x00000000004062c8 in RunBuild (argv=<optimized out>, argc=<optimized out>, this=0x7fffffffda30)
    at src/ninja.cc:971
#5  (anonymous namespace)::real_main (argc=<optimized out>, argv=<optimized out>) at src/ninja.cc:1182
#6  0x00007ffff772ff45 in __libc_start_main (main=0x402dc0 <main(int, char**)>, argc=1, argv=0x7fffffffdce8, 
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdcd8)
    at libc-start.c:287
#7  0x0000000000402fc0 in _start () at src/ninja.cc:1211
```

**Comment by colincross** [comment]
Reproducible with a test:
```C++
TEST_F(BuildWithLogTest, RebuildWithNoInputs) {
  ASSERT_NO_FATAL_FAILURE(AssertParse(&state_,
"rule touch\n"
"  command = touch\n"
"build out1: touch\n"));

  string err;

  EXPECT_TRUE(builder_.AddTarget("out1", &err));
  EXPECT_TRUE(builder_.Build(&err));
  EXPECT_EQ("", err);
  EXPECT_EQ(1u, command_runner_.commands_ran_.size());

  command_runner_.commands_ran_.clear();
  state_.Reset();
  builder_.Cleanup();
  builder_.plan_.Reset();

  fs_.Tick();

  EXPECT_TRUE(builder_.AddTarget("out1", &err));
  EXPECT_TRUE(builder_.Build(&err));
  EXPECT_EQ("", err);
  EXPECT_EQ(1u, command_runner_.commands_ran_.size());
}
```
