### ISSUE TITLE
ninja install error

### ISSUE THREAD

**Issue by gipelttil** [ninja-build/ninja#1367]
Hi I am trying to install bamtools which requires jsoncpp which requires meson which requires ninja. meson was successfully installed and I followed jsoncpp's manual to install it like no problem until the last one below (https://github.com/open-source-parsers/jsoncpp/blob/master/README.md)

sudo ninja install

I don't have permission as this is a cluster administered by admin but it will take a long time for admin to install it (to the /usr/local/lib64/) so I wanted to try to install it in my own directory (/scr1/users/guoy/bin/) - however I don't see how to do it from the ninja manual. Can anyone help me on this, esp. installing jsoncpp without error? Thank you very much!

$ ninja install
[0/1] Installing files.
Installing libjsoncpp.so.19 to /usr/local/lib64/libjsoncpp.so.19
Traceback (most recent call last):
  File "/scr1/users/guoy/bin/meson/meson", line 26, in <module>
    sys.exit(main())
  File "/scr1/users/guoy/bin/meson/meson", line 23, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "/scr1/users/guoy/bin/meson/mesonbuild/mesonmain.py", line 322, in run
    sys.exit(run_script_command(args[1:]))
  File "/scr1/users/guoy/bin/meson/mesonbuild/mesonmain.py", line 278, in run_script_command
    return cmdfunc(cmdargs)
  File "/scr1/users/guoy/bin/meson/mesonbuild/scripts/meson_install.py", line 375, in run
    do_install(datafilename)
  File "/scr1/users/guoy/bin/meson/mesonbuild/scripts/meson_install.py", line 190, in do_install
    install_targets(d)
  File "/scr1/users/guoy/bin/meson/mesonbuild/scripts/meson_install.py", line 316, in install_targets
    do_copyfile(fname, outname)
  File "/scr1/users/guoy/bin/meson/mesonbuild/scripts/meson_install.py", line 126, in do_copyfile
    shutil.copyfile(from_file, to_file)
  File "/scr1/users/guoy/bin/Python-3.6.2/Lib/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib64/libjsoncpp.so.19'
FAILED: meson-install 
/scr1/users/guoy/bin/Python-3.6.2/python3 /scr1/users/guoy/bin/meson/meson --internal install /scr1/users/guoy/bin/jsoncpp/build-shared/meson-private/install.dat
ninja: build stopped: subcommand failed.

**Comment by evmar** [comment]
Ninja only executes the commands that Meson tells it to.  From your above trace, it looks like maybe the instructions you have from jsoncpp or meson are leading you down the wrong path, but this is not a Ninja issue.
