### ISSUE TITLE
pip install ninja failed when pip>=10.0.0

### ISSUE THREAD

**Issue by fumihwh** [ninja-build/ninja#1431]
Seems this is known problem about pip>=10.0.0
https://stackoverflow.com/a/49867265

```
pip install ninja
Collecting ninja
  Using cached https://files.pythonhosted.org/packages/9c/51/332390f0e25882b8e1744ef626af70c780df66e2ba07c45428ad091be739/ninja-1.8.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/fg/mc37_2nx4sl19cv74vk3m3p80000gp/T/pip-install-1i0m4nnd/ninja/setup.py", line 6, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'
```

------------

Updated:
Even I downgrade to 9.0.3, it still failed.

```
  An error occurred while configuring with CMake.
    Command:
      "cmake" "/private/var/folders/fg/mc37_2nx4sl19cv74vk3m3p80000gp/T/pip-build-qbb7u8b5/ninja" "-G" "Unix Makefiles" "-DCMAKE_INSTALL_PREFIX:PATH=/private/var/folders/fg/mc37_2nx4sl19cv74vk3m3p80000gp/T/pip-build-qbb7u8b5/ninja/_skbuild/cmake-install" "-DPYTHON_EXECUTABLE:FILEPATH=/Users/wenhao/.virtualenvs/ml_3.6/bin/python3.6" "-DPYTHON_VERSION_STRING:STRING=3.6.5" "-DPYTHON_INCLUDE_DIR:PATH=/usr/local/var/pyenv/versions/3.6.5/include/python3.6m" "-DPYTHON_LIBRARY:FILEPATH=/usr/local/var/pyenv/versions/3.6.5/lib/libpython3.6m.a" "-DSKBUILD:BOOL=TRUE" "-DCMAKE_MODULE_PATH:PATH=/Users/wenhao/.virtualenvs/ml_3.6/lib/python3.6/site-packages/skbuild/resources/cmake" "-DCMAKE_BUILD_TYPE:STRING=Release"
    Source directory:
      /private/var/folders/fg/mc37_2nx4sl19cv74vk3m3p80000gp/T/pip-build-qbb7u8b5/ninja
    Working directory:
      /private/var/folders/fg/mc37_2nx4sl19cv74vk3m3p80000gp/T/pip-build-qbb7u8b5/ninja/_skbuild/cmake-build
  Please see CMake's output for more information.

  ----------------------------------------
  Failed building wheel for ninja
```

**Comment by esaliya** [comment]
I am facing the same issue. Is there any update on this thread?

**Comment by ozak** [comment]
Seems to be general issue of code that uses ``pip``'s internal functions. See [here](https://mail.python.org/pipermail/distutils-sig/2017-October/031642.html). Not sure what the approach is to solve the issue...e.g., [here](https://github.com/capless/warrant/issues/96). Others seems to have just taken the functions and moved into their own code (e.g., [here](https://github.com/capless/warrant/issues/96)).

**Comment by NiklasRosenstein** [comment]
It's usually sufficient to just read the file and split its lines. I suppose `parse_requirements()` takes care of comments, but converting a requirement back to a string should give you the original line again.

```python
with io.open('requirements-dev.txt', encoding='utf8') as fp:
  dev_requirements = fp.readlines()
```

**Comment by NiklasRosenstein** [comment]
PS: Where is the repository for these setup files? 🤔

**Comment by ozak** [comment]
No idea. I thought it was me who could not find it.

**Comment by ozak** [comment]
Perhaps @jcfr knows?

**Comment by jcfr** [comment]
Thanks for the heads up. New `cmake` and `ninja` wheels should be available shortly.

**Comment by jcfr** [comment]
And for future reference, the associated repositories are:
* https://github.com/scikit-build/ninja-python-distributions
* https://github.com/scikit-build/cmake-python-distributions

**Comment by ozak** [comment]
That'd be great! I'm stuck trying to install some software due to this, so prompt resolution will be much appreciated! Thanks!

**Comment by ozak** [comment]
@jcfr I downgraded ``pip`` and installed ``skbuild`` to try to install ``ninja``. But it is failing on homebrew's``python-3.7``.  I get the following

```bash
S17624:~ omer$ pip3 install ninja
Collecting ninja
  Using cached https://files.pythonhosted.org/packages/9c/51/332390f0e25882b8e1744ef626af70c780df66e2ba07c45428ad091be739/ninja-1.8.2.tar.gz
Building wheels for collected packages: ninja
  Running setup.py bdist_wheel for ninja ... error
  Complete output from command /usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/z9/fsptst_d35z1s_8c9t467dlw0000gp/T/pip-build-186pwhet/ninja/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/z9/fsptst_d35z1s_8c9t467dlw0000gp/T/tmpjvsqzprspip-wheel- --python-tag cp37:


  --------------------------------------------------------------------------------
  -- Trying "Ninja" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  -- The C compiler identification is AppleClang 9.0.0.9000039
  -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
  -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- The CXX compiler identification is AppleClang 9.0.0.9000039
  -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
  -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /private/var/folders/z9/fsptst_d35z1s_8c9t467dlw0000gp/T/pip-build-186pwhet/ninja/_cmake_test_compile/build
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Ninja" generator - success
  --------------------------------------------------------------------------------

  -- The C compiler identification is AppleClang 9.0.0.9000039
  -- The CXX compiler identification is AppleClang 9.0.0.9000039
  -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
  -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
  -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found PythonInterp: /usr/local/opt/python/bin/python3.7 (found version "3.7")
  CMake Error at CMakeLists.txt:17 (include):
    include could not find load file:

      /private/var/folders/z9/fsptst_d35z1s_8c9t467dlw0000gp/T/pip-build-186pwhet/ninja/NinjaUrls.cmake


  -- *********************************************
  -- Build Ninja from source: OFF
  -- *********************************************
  CMake Error at CMakeLists.txt:28 (message):
    Failed to determine which archive to download: 'unix_source_url' variable
    is not defined
  Call Stack (most recent call first):
    CMakeLists.txt:39 (check_archive_var)


  -- Configuring incomplete, errors occurred!
  See also "/private/var/folders/z9/fsptst_d35z1s_8c9t467dlw0000gp/T/pip-build-186pwhet/ninja/_skbuild/macosx-10.12-x86_64-3.7/cmake-build/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 532, in setup
      languages=cmake_languages
    File "/usr/local/lib/python3.7/site-packages/skbuild/cmaker.py", line 224, in configure
      os.path.abspath(CMAKE_BUILD_DIR)))

  An error occurred while configuring with CMake.
    Command:
      "cmake" "/private/var/folders/z9/fsptst_d35z1s_8c9t467dlw0000gp/T/pip-build-186pwhet/ninja" "-G" "Ninja" "-DCMAKE_INSTALL_PREFIX:PATH=/private/var/folders/z9/fsptst_d35z1s_8c9t467dlw0000gp/T/pip-build-186pwhet/ninja/_skbuild/macosx-10.12-x86_64-3.7/cmake-install" "-DPYTHON_EXECUTABLE:FILEPATH=/usr/local/opt/python/bin/python3.7" "-DPYTHON_VERSION_STRING:STRING=3.7.0" "-DPYTHON_INCLUDE_DIR:PATH=/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/include/python3.7m" "-DPYTHON_LIBRARY:FILEPATH=/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib" "-DSKBUILD:BOOL=TRUE" "-DCMAKE_MODULE_PATH:PATH=/usr/local/lib/python3.7/site-packages/skbuild/resources/cmake" "-DCMAKE_BUILD_TYPE:STRING=Release" "-DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.6" "-DCMAKE_OSX_ARCHITECTURES:STRING=x86_64"
    Source directory:
      /private/var/folders/z9/fsptst_d35z1s_8c9t467dlw0000gp/T/pip-build-186pwhet/ninja
    Working directory:
      /private/var/folders/z9/fsptst_d35z1s_8c9t467dlw0000gp/T/pip-build-186pwhet/ninja/_skbuild/macosx-10.12-x86_64-3.7/cmake-build
  Please see CMake's output for more information.

  ----------------------------------------
  Failed building wheel for ninja
  Running setup.py clean for ninja
Failed to build ninja
Installing collected packages: ninja
  Running setup.py install for ninja ... error
    Complete output from command /usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/z9/fsptst_d35z1s_8c9t467dlw0000gp/T/pip-build-186pwhet/ninja/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/z9/fsptst_d35z1s_8c9t467dlw0000gp/T/pip-_4tf4yh_-record/install-record.txt --single-version-externally-managed --compile:


    --------------------------------------------------------------------------------
    -- Trying "Ninja" generator
    --------------------------------
    ---------------------------
    ----------------------
    -----------------
    ------------
    -------
    --
    Not searching for unused variables given on the command line.
    -- The C compiler identification is AppleClang 9.0.0.9000039
    -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
    -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- The CXX compiler identification is AppleClang 9.0.0.9000039
    -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
    -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /private/var/folders/z9/fsptst_d35z1s_8c9t467dlw0000gp/T/pip-build-186pwhet/ninja/_cmake_test_compile/build
    --
    -------
    ------------
    -----------------
    ----------------------
    ---------------------------
    --------------------------------
    -- Trying "Ninja" generator - success
    --------------------------------------------------------------------------------

    -- The C compiler identification is AppleClang 9.0.0.9000039
    -- The CXX compiler identification is AppleClang 9.0.0.9000039
    -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
    -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
    -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found PythonInterp: /usr/local/opt/python/bin/python3.7 (found version "3.7")
    CMake Error at CMakeLists.txt:17 (include):
      include could not find load file:

        /private/var/folders/z9/fsptst_d35z1s_8c9t467dlw0000gp/T/pip-build-186pwhet/ninja/NinjaUrls.cmake


    -- *********************************************
    -- Build Ninja from source: OFF
    -- *********************************************
    CMake Error at CMakeLists.txt:28 (message):
      Failed to determine which archive to download: 'unix_source_url' variable
      is not defined
    Call Stack (most recent call first):
      CMakeLists.txt:39 (check_archive_var)


    -- Configuring incomplete, errors occurred!
    See also "/private/var/folders/z9/fsptst_d35z1s_8c9t467dlw0000gp/T/pip-build-186pwhet/ninja/_skbuild/macosx-10.12-x86_64-3.7/cmake-build/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 532, in setup
        languages=cmake_languages
      File "/usr/local/lib/python3.7/site-packages/skbuild/cmaker.py", line 224, in configure
        os.path.abspath(CMAKE_BUILD_DIR)))

    An error occurred while configuring with CMake.
      Command:
        "cmake" "/private/var/folders/z9/fsptst_d35z1s_8c9t467dlw0000gp/T/pip-build-186pwhet/ninja" "-G" "Ninja" "-DCMAKE_INSTALL_PREFIX:PATH=/private/var/folders/z9/fsptst_d35z1s_8c9t467dlw0000gp/T/pip-build-186pwhet/ninja/_skbuild/macosx-10.12-x86_64-3.7/cmake-install" "-DPYTHON_EXECUTABLE:FILEPATH=/usr/local/opt/python/bin/python3.7" "-DPYTHON_VERSION_STRING:STRING=3.7.0" "-DPYTHON_INCLUDE_DIR:PATH=/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/include/python3.7m" "-DPYTHON_LIBRARY:FILEPATH=/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib" "-DSKBUILD:BOOL=TRUE" "-DCMAKE_MODULE_PATH:PATH=/usr/local/lib/python3.7/site-packages/skbuild/resources/cmake" "-DCMAKE_BUILD_TYPE:STRING=Release" "-DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.6" "-DCMAKE_OSX_ARCHITECTURES:STRING=x86_64"
      Source directory:
        /private/var/folders/z9/fsptst_d35z1s_8c9t467dlw0000gp/T/pip-build-186pwhet/ninja
      Working directory:
        /private/var/folders/z9/fsptst_d35z1s_8c9t467dlw0000gp/T/pip-build-186pwhet/ninja/_skbuild/macosx-10.12-x86_64-3.7/cmake-build
    Please see CMake's output for more information.

    ----------------------------------------
Command "/usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/z9/fsptst_d35z1s_8c9t467dlw0000gp/T/pip-build-186pwhet/ninja/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/z9/fsptst_d35z1s_8c9t467dlw0000gp/T/pip-_4tf4yh_-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/z9/fsptst_d35z1s_8c9t467dlw0000gp/T/pip-build-186pwhet/ninja/
```

Any ideas? Thanks!

**Comment by jcfr** [comment]
If you wait few more hours, a new release of the wheel should be available.

We just released a new version of [scikit-build](https://pypi.org/project/scikit-build/#history), the package 
supporting the generation of the wheels.


> CMake Error at CMakeLists.txt:17 (include):
>      include could not find load file:
>
>        /private/var/folders/z9/fsptst_d35z1s_8c9t467dlw0000gp/T/pip-build-186pwhet/ninja/NinjaUrls.cmake

We will also add a test checking that the wheel can be generated from the source distribution.

**Comment by ozak** [comment]
Sure! Thanks!

**Comment by jcfr** [comment]
Thanks for your patience.

This issue can be closed. New wheels for both CMake and Ninja have been released.

* https://pypi.org/project/ninja/1.8.2.post1/#files

  * we are also thinking to create a `ninja-1.8.2.post2` released based of https://github.com/kitware/ninja#readme . This release would include make-style jobserver support and also dynamic dependency discovery needed for Fortran builds

* https://pypi.org/project/cmake/3.11.4/#files   (wheels for CMake 3.12.0 on the way)

**Comment by jhasse** [comment]
Thank you for fixing this :)

**Comment by Widney14** [comment]
> Thanks for the heads up. New `cmake` and `ninja` wheels should be available shortly.

Hello, is there  a way to install ninja without it setup.py reference to the git repository?
