### ISSUE TITLE
Windows: fopen cannot create file if its full path is longer than 254 chars

### ISSUE THREAD

**Issue by volth** [ninja-build/ninja#1514]
Chromium build started from a directory which is ~30 chars long fails with
```
[3572/20749] STAMP obj/services/network/public/mojom/mojom_ip_address_shared_cpp_sources__jumbo_merge.stamp
[3573/20749] STAMP obj/services/metrics/public/mojom/mojom_blink__jumbo_merge.stamp
ninja: error: WriteFile(__services_network_public_mojom_mutable_network_traffic_annotation_interface_shared_cpp_sources__jumbo_merge___build_toolchain_win_win_clang_x64__rule.rsp): Unable to create file. No such file or directory
```

The filename "__services_network_public_mojom_mutable_network_traffic_annotation_interface_shared_cpp_sources__jumbo_merge___build_toolchain_win_win_clang_x64__rule.rsp" is 155 chars long + paths inside Chromium source tree + prefix caused by superviser package manager (nixpkgs) result in full path being about 260 chars long

Alhough ```fopen()```'s argument has length of only 155 chars, it hits the limit set for the full path.

I propose to use raw WinAPI instead of ```fopen()``` and add ```\\?\``` prefix to the argument to allow paths up to 32767 chars long.

**Comment by atetubou** [comment]
I think it is better to file a bug to crbug too so that jumbo build generates shorter file name.

**Comment by volth** [comment]
> It's possible to lift the MAX_PATH limitation via a manifest setting, see https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file#paths. I'm not sure if this will apply to fopen though

That seems to require Windows 10 and affects only Unicode API (CreateFileW but not CreateFileA)

**Comment by jhasse** [comment]
We're using neither `CreateFileW` nor `CreateFileA` but `fopen`. I wonder if the setting will affect it. If not, it might affect `_wfopen` which is needed for #1195 anyway.

**Comment by volth** [comment]
If we will fix it by adding the manifest, what about the next person who step into this bug?
Will he be advised to upgrade Windows to Windows 10?

**Comment by jhasse** [comment]
I doubt that this would be an option for him, otherwise he would have done it already.

**Comment by volth** [comment]
Well, even if ```ninja``` managed to create the file with long path (I fixed it with https://github.com/ninja-build/ninja/compare/master...volth:patch-1), `it does not fix Chromium jumbo build: ```python``` fails to open the file :(

```
Traceback (most recent call last):
  File "../../build/config/merge_for_jumbo.py", line 144, in <module>
    main()
  File "../../build/config/merge_for_jumbo.py", line 113, in main
    with open(args.file_list) as file_list_file:
IOError: [Errno 2] No such file or directory: '__services_network_public_mojom_mutable_network_traffic_annotation_interface_shared_cpp_sources__jumbo_merge___build_toolchain_win_win_clang_x64__rule.rsp'
```

So fixing it in Chromium would be a right solution.
Although, as nixpkgs adds long prefixes, I anticipate more bugs like this one so I will be happy to see ```ninja``` and ```python``` and other tools be able to work with long paths.

**Comment by volth** [comment]
setting ```HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem@LongPathsEnabled``` to ```1``` did not help

**Comment by jhasse** [comment]
So it probably only applies to `_wfopen`.

**Comment by progician** [comment]
I would still be very happy if our toolchain can be moved over Win10 long file paths and drop these ridiculous subst's and other magic to make complicated software build on Windows.

**Comment by orion160** [comment]
What is the actual state of #1515 ?
