### ISSUE TITLE
Using too many threads on CircleCI

### ISSUE THREAD

**Issue by dan-ryan** [ninja-build/ninja#1530]
I've found Ninja was too resource intensive on CircleCI (4GB, 2 CPU box, running a docker image) and it wouldn't finish the build because of it. 
It would crash with:
```
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
...
ninja: build stopped: subcommand failed.
```

I solved this issue with `ninja -j 4`.
Now I'm using Gradle with a Cmake file to build an Android product with the NDK. It seems to keep running out of ram while building the C++ library. I don't believe I have any control how many threads ninja runs through Gradle, I'm unsure how to reduce the thread amount. 
Is there some kind environment flag I can set? Could Ninja work out a better default thread count on CircleCI? 

```
01:45:39.318 [LIFECYCLE] [org.gradle.api.Project] 1 warning generated.
01:45:39.443 [LIFECYCLE] [org.gradle.api.Project] [76/144] Building CXX object CMakeFiles/ce.dir/source/DeviceInformation.cpp.o
01:45:39.846 [LIFECYCLE] [org.gradle.api.Project] 
01:45:39.846 [ERROR] [org.gradle.api.Project] AAPT2 aapt2-3.3.1-5013011-linux Daemon #0: Unexpectedly exit.
01:45:40.035 [ERROR] [org.gradle.api.Project] AAPT2 aapt2-3.3.1-5013011-linux Daemon #1: Unexpectedly exit.
01:45:40.050 [ERROR] [org.gradle.api.Project] AAPT2 aapt2-3.3.1-5013011-linux Daemon #3: Unexpectedly exit.
01:45:40.115 [ERROR] [org.gradle.api.Project] AAPT2 aapt2-3.3.1-5013011-linux Daemon #7: Unexpectedly exit.
01:45:40.128 [ERROR] [org.gradle.api.Project] AAPT2 aapt2-3.3.1-5013011-linux Daemon #4: Unexpectedly exit.
01:45:40.257 [ERROR] [org.gradle.api.Project] AAPT2 aapt2-3.3.1-5013011-linux Daemon #2: Unexpectedly exit.
01:45:40.316 [ERROR] [org.gradle.api.Project] AAPT2 aapt2-3.3.1-5013011-linux Daemon #6: Unexpectedly exit.
01:45:40.331 [ERROR] [org.gradle.api.Project] AAPT2 aapt2-3.3.1-5013011-linux Daemon #5: Unexpectedly exit.
01:45:40.749 [DEBUG] [org.gradle.internal.remote.internal.inet.SocketConnection] Discarding EOFException: java.io.EOFException
01:45:40.749 [ERROR] [org.gradle.launcher.daemon.client.DaemonClient] The message received from the daemon indicates that the daemon has disappeared.
Build request sent: Build{id=448d9a4d-ca44-47fe-94df-3c9578f2defe, currentDir=/home/circleci/CricHQ-Android}
Attempting to read last messages from the daemon log...
01:45:41.355 [ERROR] [org.gradle.launcher.daemon.client.DaemonClient] Daemon pid: 520
  log file: /home/circleci/.gradle/daemon/4.10.1/daemon-520.out.log
----- Last  20 lines from daemon log file - daemon-520.out.log -----
01:45:39.443 [LIFECYCLE] [org.gradle.api.Project] [76/144] Building CXX object CMakeFiles/ce.dir/source/DeviceInformation.cpp.o
01:45:39.846 [ERROR] [org.gradle.api.Project] AAPT2 aapt2-3.3.1-5013011-linux Daemon #0: Unexpectedly exit.
01:45:40.035 [ERROR] [org.gradle.api.Project] AAPT2 aapt2-3.3.1-5013011-linux Daemon #1: Unexpectedly exit.
01:45:40.050 [ERROR] [org.gradle.api.Project] AAPT2 aapt2-3.3.1-5013011-linux Daemon #3: Unexpectedly exit.
01:45:40.115 [ERROR] [org.gradle.api.Project] AAPT2 aapt2-3.3.1-5013011-linux Daemon #7: Unexpectedly exit.
01:45:40.128 [ERROR] [org.gradle.api.Project] AAPT2 aapt2-3.3.1-5013011-linux Daemon #4: Unexpectedly exit.
01:45:40.131 [LIFECYCLE] [org.gradle.api.Project] [77/144] Building CXX object CMakeFiles/ce.dir/source/EventDeviceInformation.cpp.o
01:45:40.131 [LIFECYCLE] [org.gradle.api.Project] FAILED: CMakeFiles/ce.dir/source/EventDeviceInformation.cpp.o 
01:45:40.131 [LIFECYCLE] [org.gradle.api.Project] /opt/android/android-ndk-r17b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=i686-none-linux-android --gcc-toolchain=/opt/android/android-ndk-r17b/toolchains/x86-4.9/prebuilt/linux-x86_64 --sysroot=/opt/android/android-ndk-r17b/sysroot  -Dce_EXPORTS -I/home/circleci/CricHQ-Android/CricHQ/src/main/jni/CricEngine/source -I/home/circleci/CricHQ-Android/CricHQ/src/main/jni/CricEngine/source/lib/hopscotch-map -I/home/circleci/CricHQ-Android/CricHQ/src/main/jni/CricEngine/source/lib/rapidjson -I/home/circleci/CricHQ-Android/CricHQ/src/main/jni/CricEngine/source/lib/rapidjson/error -I/home/circleci/CricHQ-Android/CricHQ/src/main/jni/CricEngine/source/lib/CCF/source -I/home/circleci/CricHQ-Android/CricHQ/src/main/jni/CricEngine/source/lib/CCF/source/lib -I/home/circleci/CricHQ-Android/CricHQ/src/main/jni/CricEngine/source/lib/Fabric -isystem /opt/android/android-ndk-r17b/sources/cxx-stl/llvm-libc++/include -isystem /opt/android/android-ndk-r17b/sources/android/support/include -isystem /opt/android/android-ndk-r17b/sources/cxx-stl/llvm-libc++abi/include -isystem /opt/android/android-ndk-r17b/sysroot/usr/include/i686-linux-android -D__ANDROID_API__=19 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mstackrealign -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11  -O0 -fno-limit-debug-info  -g -funwind-tables -fno-optimize-sibling-calls -frtti -fexceptions -fPIC   -std=gnu++1z -MD -MT CMakeFiles/ce.dir/source/EventDeviceInformation.cpp.o -MF CMakeFiles/ce.dir/source/EventDeviceInformation.cpp.o.d -o CMakeFiles/ce.dir/source/EventDeviceInformation.cpp.o -c /home/circleci/CricHQ-Android/CricHQ/src/main/jni/CricEngine/source/EventDeviceInformation.cpp
01:45:40.131 [LIFECYCLE] [org.gradle.api.Project] In file included from /home/circleci/CricHQ-Android/CricHQ/src/main/jni/CricEngine/source/EventDeviceInformation.cpp:13:
01:45:40.131 [LIFECYCLE] [org.gradle.api.Project] In file included from /home/circleci/CricH
01:45:40.131 [LIFECYCLE] [org.gradle.api.Project] Q-Android/CricHQ/src/main/jni/CricEngine/source/CECricEngine.hpp:14:
01:45:40.131 [LIFECYCLE] [org.gradle.api.Project] In file included from /home/circleci/CricHQ-Android/CricHQ/src/main/jni/CricEngine/source/lib/hopscotch-map/hopscotch_map.h:36:
01:45:40.131 [LIFECYCLE] [org.gradle.api.Project] /home/circleci/CricHQ-Android/CricHQ/src/main/jni/CricEngine/source/lib/hopscotch-map/hopscotch_hash.h:1743:39: warning: comparison 'unsigned int' <= 4294967295 is always true [-Wtautological-constant-compare]
01:45:40.132 [LIFECYCLE] [org.gradle.api.Project]             return (bucket_count - 1) <= std::numeric_limits<truncated_hash_type>::max();
01:45:40.132 [LIFECYCLE] [org.gradle.api.Project]                    ~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
01:45:40.132 [LIFECYCLE] [org.gradle.api.Project] fatal error: error in backend: IO failure on output stream.
01:45:40.257 [ERROR] [org.gradle.api.Project] AAPT2 aapt2-3.3.1-5013011-linux Daemon #2: Unexpectedly exit.
01:45:40.316 [ERROR] [org.gradle.api.Project] AAPT2 aapt2-3.3.1-5013011-linux Daemon #6: Unexpectedly exit.
01:45:40.331 [ERROR] [org.gradle.api.Project] AAPT2 aapt2-3.3.1-5013011-linux Daemon #5: Unexpectedly exit.
----- End of the daemon log -----

01:45:41.416 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: connection stop
01:45:41.424 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
01:45:41.440 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
01:45:41.440 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
01:45:41.440 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
01:45:41.440 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
01:45:41.440 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
01:45:41.440 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
01:45:41.440 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]  Run with --scan to get full insights.
01:45:41.441 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
01:45:41.441 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
01:45:41.441 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.launcher.daemon.client.DaemonDisappearedException: Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
01:45:41.441 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.client.DaemonClient.handleDaemonDisappearance(DaemonClient.java:242)
01:45:41.441 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.client.DaemonClient.monitorBuild(DaemonClient.java:218)
01:45:41.441 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.client.DaemonClient.executeBuild(DaemonClient.java:179)
01:45:41.442 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:142)
01:45:41.442 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:93)
01:45:41.442 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:52)
01:45:41.442 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:207)
01:45:41.442 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:402)
01:45:41.442 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:375)
01:45:41.442 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:37)
01:45:41.442 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:23)
01:45:41.442 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:368)
01:45:41.442 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:298)
01:45:41.442 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.Main.doAction(Main.java:36)
01:45:41.442 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
01:45:41.442 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:45:41.442 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:45:41.442 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:45:41.442 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.lang.reflect.Method.invoke(Method.java:498)
01:45:41.442 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
01:45:41.442 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
01:45:41.442 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
01:45:41.442 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:45:41.442 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:45:41.442 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:45:41.442 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.lang.reflect.Method.invoke(Method.java:498)
01:45:41.442 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
01:45:41.442 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
01:45:41.442 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
01:45:41.442 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
01:45:41.442 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
01:45:41.442 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org

```

**Comment by jhasse** [comment]
Starting with CMake 3.12 you will be able to set [`CMAKE_BUILD_PARALLEL_LEVEL`](https://cmake.org/cmake/help/v3.12/envvar/CMAKE_BUILD_PARALLEL_LEVEL.html#envvar:CMAKE_BUILD_PARALLEL_LEVEL). The Android NDK still uses 3.10 though: https://issuetracker.google.com/issues/111569282

**Comment by dan-ryan** [comment]
Looks like you can point to a CMake version outside of Android Studio. 
Any examples of how I use CMAKE_BUILD_PARALLEL_LEVEL?

**Comment by dan-ryan** [comment]
Doesn't seem to be working.
```
        externalNativeBuild {
            cmake {
                arguments "-DANDROID_NATIVE_API_LEVEL=19", "-DANDROID_TOOLCHAIN=clang", "-DCMAKE_BUILD_PARALLEL_LEVEL=1"
...
```

> CMake Warning:
>   Manually-specified variables were not used by the project:
> 
>     CMAKE_BUILD_PARALLEL_LEVEL

**Comment by jhasse** [comment]
I think it's only an environment variable, so you can't pass it to CMake directly.

**Comment by dan-ryan** [comment]
Yes, you are right, the only project that I found online using this was wrong. 
"CMAKE_BUILD_PARALLEL_LEVEL 4" solved the issue for the CircleCI build. Though to me it sounds like there is a bug with Ninja picking the wrong amount of threads on CircleCI. Being it's a 2 CPU box I thought it would be 4 by default.

**Comment by jhasse** [comment]
The amount of threads depends on the number of logical CPU cores. If the 2 CPU box also has 2 logical CPU cores, Ninja would pick 3 threads. But if both physical CPUs have, let's say, 4 cores and support SMT, that would mean 16 logical cores and ninja would spawn 18 threads. See: https://github.com/ninja-build/ninja/blob/master/src/ninja.cc#L232

I don't know how CircleCI's machines look like, in general we don't want to add any special checks for one CI service.

If you have more information or there's a bug in the way we get the number of logical CPU cores, please reopen.

**Comment by jhasse** [comment]
On second thought ... this might actually be #1278!

**Comment by kiwixz** [comment]
Actually CircleCI is to blame for this issue: https://ideas.circleci.com/ideas/CCI-I-578.

**Comment by dan-ryan** [comment]
Ok good to know. Can people vote the issue up so it gets looked at? 
I guess another solution is to reduce the threads if the ram is too low but that probably have the same issue that the amount of free ram is reported wrong :P
