### ISSUE TITLE
Got error when built ninja on Centos6.7

### ISSUE THREAD

**Issue by kindred77** [ninja-build/ninja#1586]
./configure.py --bootstrap

bootstrapping ninja...
warning: A compatible version of re2c (>= 0.11.3) was not found; changes to src/*.in.cc will not affect your build.
wrote build.ninja.
bootstrap complete.  rebuilding...
./ninja: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by ./ninja)
./ninja: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./ninja)
./ninja: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./ninja)
Traceback (most recent call last):
  File "./configure.py", line 700, in <module>
    subprocess.check_call(rebuild_args)
  File "/usr/lib64/python2.6/subprocess.py", line 505, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./ninja']' returned non-zero exit status 1

**Comment by kindred77** [comment]
It seams libstdc++ does not match gcc.
Close now.
