### ISSUE TITLE
Install Via pip Fails Due to Dependency scikit-build

### ISSUE THREAD

**Issue by AntumDeluge** [ninja-build/ninja#1608]
I believe that `scikit-build` should be added as a dependency in `pip install` as I get the following error if it is not installed:

```sh
$ pip install ninja
Collecting ninja
  Using cached https://files.pythonhosted.org/packages/dd/96/e2ec4acccb8dee33b4987f553d531d61e3081c8d4cfbce249655dfe23906/ninja-1.9.0.post1.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-av7tfuja/ninja/setup.py", line 7, in <module>
        from skbuild import setup
    ModuleNotFoundError: No module named 'skbuild'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-av7tfuja/ninja/
```

---
**Edit:** System & platform information:

OS: Microsoft Windows 10 64-bit
Python & pip info:
```sh
$ python --version
Python 3.7.4

$ python -c 'import sys; print("64-bit: {}".format(sys.maxsize > 2**32))'
64-bit: True

$ pip --version
pip 19.1 from /usr/lib/python3.7/site-packages/pip (python 3.7)

$ pip search ninja
ninja (1.9.0.post1)                               - Ninja is a small build
                                                    system with a focus on
                                                    speed
...
```

**Comment by jhasse** [comment]
The ninja pip package is actually not by us, please file an issue here: https://github.com/scikit-build/ninja-python-distributions

**Comment by AntumDeluge** [comment]
Thanks @jhasse. I will do that.
