### ISSUE TITLE
Can't build, re2c -V option not valid

### ISSUE THREAD

**Issue by LeeHudsonDLS** [ninja-build/ninja#1723]
Hi,
I'm not sure what's going on here but when I run ./configure.py --bootstrap I get the error:

terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::erase
Traceback (most recent call last):
  File "./configure.py", line 475, in <module>
    if has_re2c():
  File "./configure.py", line 472, in has_re2c
    return int(proc.communicate()[0], 10) >= 1103
ValueError: invalid literal for int() with base 10: ''

I've traced this to the has_re2c() method in configure.py that tried to determine the version of re2c using the -V option. On my version of re2c I can see that -V isn't an option, -v is. Even with -v my version of re2c (1.1) returns a string "re2c 1.1" which obviously can't be compared against 1103 as in the script. Am I missing something here?

**Comment by LeeHudsonDLS** [comment]
My version of re2c was too old
