### ISSUE TITLE
Ninja hanging

### ISSUE THREAD

**Issue by Appadeia** [ninja-build/ninja#1752]
Ninja seems to hang when parsing the build.ninja generated by CMake with [Ikona](https://invent.kde.org/kde/ikona). From what I can tell, it's hanging on this section:

```
build ../src/rs/target/release/libikonars.so: CUSTOM_COMMAND ../src/rs/src/ikona/icons/mod.rs ../src/rs/src/ikona/icons/tests.rs ../src/rs/src/ikona/lib.rs ../src/rs/src/capi/capi.rs
  COMMAND = cd /home/cdblack/kde/git/ikona/src/rs && /home/cdblack/.cargo/bin/cargo build --release            
  DESC = Generating ../src/rs/target/release/libikonars.so yaoi
  restat = 1 
```

(commands will vary, of course.)

Ninja version: 1.10.0

**Comment by jhasse** [comment]
Can you retry with a debugger and break to see where in the code it hangs?

**Comment by Appadeia** [comment]
```
(gdb) run
Starting program: /usr/bin/ninja -j1
[0/12] Generating ../src/rs/target/release/libikonars.so[Detaching after vfork from child process 12954]
^C
Program received signal SIGINT, Interrupt.
0x00007ffff7ea5b6b in __ppoll (fds=0x5555555af290, nfds=1, timeout=<optimized out>, sigmask=0x5555555b0f00) at ../sysdeps/unix/sysv/linux/ppoll.c:44
44        return SYSCALL_CANCEL (ppoll_time64, fds, nfds, timeout, sigmask, _NSIG / 8);
Missing separate debuginfos, use: zypper install libgcc_s1-debuginfo-10.0.1+git174776-1.1.x86_64 libstdc++6-debuginfo-10.0.1+git174776-1.1.x86_64
(gdb) where
#0  0x00007ffff7ea5b6b in __ppoll (fds=0x5555555af290, nfds=1, timeout=<optimized out>, sigmask=0x5555555b0f00) at ../sysdeps/unix/sysv/linux/ppoll.c:44
#1  0x000055555557857f in ppoll (__ss=0x5555555b0f00, __timeout=0x0, __nfds=1, __fds=0x5555555af290) at /usr/include/bits/poll2.h:77
#2  SubprocessSet::DoWork (this=0x5555555b0cd0) at src/subprocess-posix.cc:250
#3  RealCommandRunner::WaitForCommand (this=0x5555555b0cc0, result=0x7fffffffd270) at src/build.cc:715
#4  0x00005555555772ec in Builder::Build (this=0x7fffffffd490, err=0x7fffffffd590) at src/build.cc:856
#5  0x000055555557a429 in (anonymous namespace)::NinjaMain::RunBuild (argv=0x7fffffffd8d8, argc=0, this=0x7fffffffd5b0) at src/ninja.cc:1221
#6  (anonymous namespace)::real_main (argc=0, argv=0x7fffffffd8d8) at src/ninja.cc:1424
#7  0x00005555555589cb in main (argc=<optimized out>, argv=<optimized out>) at src/ninja.cc:1453
(gdb)
```

**Comment by jhasse** [comment]
Looks to me that a command is hanging, not Ninja itself. Not much we can do about that, sorry.
