### ISSUE TITLE
gn gen out/Default not working. what am I doing wrong?

### ISSUE THREAD

**Issue by Apelsin2020** [ninja-build/ninja#1863]
Trying to build chromium on my computer, as indicated here. But I got stuck here at this point:

`gn gen out / Default`

When executing this command, I get the following

```
e:\chromium5\src>gn gen out/Default
Traceback (most recent call last):
  File "e:/chromium5/src/build/vs_toolchain.py", line 577, in <module>
    sys.exit(main())
  File "e:/chromium5/src/build/vs_toolchain.py", line 573, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "e:/chromium5/src/build/vs_toolchain.py", line 551, in GetToolchainDir
    win_sdk_dir = SetEnvironmentAndGetSDKDir()
  File "e:/chromium5/src/build/vs_toolchain.py", line 544, in SetEnvironmentAndGetSDKDir
    return NormalizePath(os.environ['WINDOWSSDKDIR'])
  File "E:\depot\bootstrap-3_8_0_chromium_8_bin\python\bin\lib\os.py", line 425, in __getitem__
    return self.data[key.upper()]
KeyError: 'WINDOWSSDKDIR'
ERROR at //build/config/win/visual_studio_version.gni:27:7: Script returned non-zero exit code.
      exec_script("../../vs_toolchain.py", [ "get_toolchain_dir" ], "scope")
      ^----------
Current dir: e:/chromium5/src/out/Default/
Command: E:/depot/bootstrap-3_8_0_chromium_8_bin/python/bin/python.exe e:/chromium5/src/build/vs_toolchain.py get_toolchain_dir
Returned 1.
See //third_party/angle/gni/angle.gni:26:5: whence it was imported.
    import("//build/config/win/visual_studio_version.gni")
    ^----------------------------------------------------
See //ui/accessibility/BUILD.gn:19:3: whence it was imported.
  import("//build/toolchain/win/midl.gni")
  ^--------------------------------------
See //BUILD.gn:156:7: which caused the file to be included.
      "//ui/accessibility:accessibility_perftests",
      ^-------------------------------------------
```

I tried to download it again, but nothing helps, what could be the reason?

**Comment by jhasse** [comment]
Both GN and Chromium aren't Ninja, please ask them instead.
