### ISSUE TITLE
ninja -t browse --port=8000 --no-browser mytarget python exception

### ISSUE THREAD

**Issue by gevorgyana** [ninja-build/ninja#1874]
Reproduce:
- run `ninja -t browse --port=8000 --no-browser $mytarget`
- see this
Traceback (most recent call last):                                                        
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread          
    self.finish_request(request, client_address)                                          
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request                  
    self.RequestHandlerClass(request, client_address, self)                               
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__                        
    self.handle()                                                                         
  File "/usr/lib/python3.8/http/server.py", line 427, in handle                           
    self.handle_one_request()                                                             
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request               
    method()                                                                              
  File "<stdin>", line 186, in do_GET                                                     
  File "<stdin>", line 65, in html_escape                                                 
AttributeError: module 'cgi' has no attribute 'escape'

Running Ubuntu 20.04, Python3 as you can see.
Ninja v.1.10.0

**Comment by jhasse** [comment]
fixed by #1744
