### ISSUE TITLE
Ninja brwosing tool's Python script needs to be updated.

### ISSUE THREAD

**Issue by gevorgyana** [ninja-build/ninja#1883]
Just open an arbitrary project, type `ninja -t browse` and see the following:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "<stdin>", line 183, in do_GET
  File "<stdin>", line 133, in generate_html
  File "<stdin>", line 65, in html_escape
AttributeError: module 'cgi' has no attribute 'escape'
```

**Comment by jhasse** [comment]
fixed by #1744
