### ISSUE TITLE
build failure on AIX 6.1

### ISSUE THREAD

**Issue by yuzhichang** [ninja-build/ninja#2069]
I failed to build ninja master tip on AIX 6.1.
```
root@aix6:/zhichyu/ninja-orig$ oslevel -s
6100-07-00-0000
root@aix6:/zhichyu/ninja-orig$ uname -a
AIX aix6 1 6 00C553DC4C00

root@aix6:/zhichyu/ninja-orig$ git log|head -n 1
commit e234b25bb51a4d3ce5376febb4ad9a11e77d5ca3

root@aix6:/zhichyu/ninja-orig$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/opt/freeware/libexec/gcc/powerpc-ibm-aix6.1.1.0/6.3.0/lto-wrapper
Target: powerpc-ibm-aix6.1.1.0
Configured with: ../gcc-6.3.0/configure --with-as=/usr/bin/as --with-ld=/usr/bin/ld --enable-languages=c,c++,fortran --prefix=/opt/freeware --mandir=/opt/freeware/man --infodir=/opt/freeware/info --enable-version-specific-runtime-libs --disable-nls --enable-decimal-float=dpd --with-cloog=no --with-ppl=no --disable-libstdcxx-pch --enable-__cxa_atexit --enable-bootstrap --host=powerpc-ibm-aix6.1.1.0
Thread model: aix
gcc version 6.3.0 (GCC) 

root@aix6:/zhichyu/ninja-orig$ python ./configure.py --bootstrap
bootstrapping ninja...
warning: A compatible version of re2c (>= 0.11.3) was not found; changes to src/*.in.cc will not affect your build.
./src/json.cc: In function 'std::__cxx11::string EncodeJSONString(const string&)':
./src/json.cc:36:18: warning: comparison is always true due to limited range of data type [-Wtype-limits]
     else if (0x0 <= c && c < 0x20) {
              ~~~~^~~~
In file included from /usr/include/net/if.h:140:0,
                 from /usr/include/sys/corral.h:24,
                 from /usr/include/libperfstat.h:28,
                 from ./src/util.cc:49:
/usr/include/netinet/in.h:542:8: error: redefinition of 'struct sockaddr'
 struct sockaddr {
        ^~~~~~~~
In file included from /usr/include/net/if.h:130:0,
                 from /usr/include/sys/corral.h:24,
                 from /usr/include/libperfstat.h:28,
                 from ./src/util.cc:49:
/opt/freeware/lib/gcc/powerpc-ibm-aix6.1.1.0/6.3.0/include-fixed/sys/socket.h:320:8: error: previous definition of 'struct sockaddr'
 struct sockaddr {
        ^~~~~~~~
when running:  c++ -MMD -MT build/util.o -MF build/util.o.d -g -Wall -Wextra -Wno-deprecated -Wno-missing-field-initializers -Wno-unused-parameter -fno-rtti -fno-exceptions -pipe '-DNINJA_PYTHON="python"' -O2 -DNDEBUG -fdiagnostics-color -D__STDC_FORMAT_MACROS -D_LARGE_FILES -I. -c ./src/util.cc -o build/util.o
Traceback (most recent call last):
  File "./configure.py", line 522, in <module>
    objs += cxx(name, variables=cxxvariables)
  File "./configure.py", line 287, in cxx
    return n.build(built(name + objext), 'cxx', src(name + '.cc'), **kwargs)
  File "./configure.py", line 169, in build
    self._run_command(self._expand(cmd, local_vars))
  File "./configure.py", line 194, in _run_command
    subprocess.check_call(cmdline, shell=True)
  File "/opt/freeware/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'c++ -MMD -MT build/util.o -MF build/util.o.d -g -Wall -Wextra -Wno-deprecated -Wno-missing-field-initializers -Wno-unused-parameter -fno-rtti -fno-exceptions -pipe '-DNINJA_PYTHON="python"' -O2 -DNDEBUG -fdiagnostics-color -D__STDC_FORMAT_MACROS -D_LARGE_FILES -I. -c ./src/util.cc -o build/util.o' returned non-zero exit status 1

```

**Comment by yuzhichang** [comment]
I managed to build ninja on AIX 6.1 with following changes:
- Patch `/opt/freeware/lib/gcc/powerpc-ibm-aix6.1.1.0/6.3.0/include-fixed/sys/socket.h`:
```
diff -Naur old/socket.h new/socket.h
--- old/socket.h	2022-01-12 14:48:29.542006588 +0800
+++ new/socket.h	2022-01-12 14:48:34.614090976 +0800
@@ -298,6 +298,13 @@
 #endif
 
 /*
+ * sockaddr also has a similar definition in inet/in.h
+ * If we need to change this here, it must be changed
+ * in inet/in.h also.
+ */
+#if !defined(__SOCKADDR_T)
+#define __SOCKADDR_T
+/*
  * Family typedef
  */
 #ifndef _SA_FAMILY_T
@@ -324,6 +331,7 @@
 };
 
 #endif /* COMPAT_43 */
+#endif /* (!__SOCKADDR_T) */
 
 
 /*
```

Note: I'm inspired by comparing `sys/socket.h` of GCC between AIX 6.1 and AIX 7.1.(Both are rpm downloaded from `http://www.oss4aix.org/download/everything/RPMS/`)

- Patch `configure.py`:
```
--- ninja-orig/configure.py     2022-01-08 23:32:02.000000000 +0800
+++ ninja-new/configure.py      2020-10-22 05:04:34.000000000 +0800
@@ -100,7 +100,7 @@
          return self._platform == 'aix'
  
      def is_os400_pase(self):
-         return self._platform == 'os400' or os.uname().sysname.startswith('OS400')
+         return self._platform == 'os400'
  
      def uses_usr_local(self):
          return self._platform in ('freebsd', 'openbsd', 'bitrig', 'dragonfly', 'netbsd')
```

Note: Python3 doesn't work on AIX 6.1 nor 7.1. I have to use python 2.7. `os.uname()` returns a tuple in python2, a posix.uname_result object in python3.
