### ISSUE TITLE
Segfault when opening build log – unable to do anything with ninja

### ISSUE THREAD

**Issue by S-Rafael** [ninja-build/ninja#2117]
When configuring a build with CMake, or trying to execute against existing `build.ninja` or pretty much doing anything else, I get a segfault right away, before seeing any output to stdout.

This happens both on 1.10.2 and on current master.

Output from CMake:
```
CMake Error:
  Running

   '/usr/local/bin/ninja' '-C' '/path/to/project/build/CMakeFiles/CMakeTmp' '-t' 'recompact'

  failed with:

   Segmentation fault
```

After this failure, the directory `CMakeTmp` is empty.

When running a debug build of ninja on an existing configured project, I collected the following backtrace:
```
Program received signal SIGSEGV, Segmentation fault.
0x000055555556c39a in BuildLog::Load (this=<error reading variable: Cannot access memory at address 0x7ffffffbd8d8>, path=<error reading variable: Cannot access memory at address 0x7ffffffbd8d0>, err=<error reading variable: Cannot access memory at address 0x7ffffffbd8c8>) at src/build_log.cc:261
261     LoadStatus BuildLog::Load(const string& path, string* err) {
(gdb) bt
#0  0x000055555556c39a in BuildLog::Load (this=<error reading variable: Cannot access memory at address 0x7ffffffbd8d8>, 
    path=<error reading variable: Cannot access memory at address 0x7ffffffbd8d0>, 
    err=<error reading variable: Cannot access memory at address 0x7ffffffbd8c8>)
    at src/build_log.cc:261
#1  0x000055555555f42a in (anonymous namespace)::NinjaMain::OpenBuildLog (this=0x7fffffffdbc0, recompact_only=false)
    at src/ninja.cc:1239
#2  0x0000555555560ae1 in (anonymous namespace)::real_main (argc=0, argv=0x7fffffffdf30)
    at src/ninja.cc:1553
#3  0x0000555555560dde in main (argc=1, argv=0x7fffffffdf28) at src/ninja.cc:1601
```
This is not the same issue as #1978; removing `.ninja_deps` and `.ninja_log` didn't stop the crash.

**Comment by S-Rafael** [comment]
OK, I've got it working again – sorry for the scare. I believe it was an intermittent state after a library update somewhere else in the system.
