### ISSUE TITLE
Lfs build error

### ISSUE THREAD

**Issue by astronaut64** [ninja-build/ninja#2285]
Hello, when i try build ninja in linux from scratch display this error:
```
(lfs chroot) I have no name!:/src/ninja-1.11.1# python3 configure.py --bootstrap 
/src/ninja-1.11.1/configure.py:26: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
  import pipes
bootstrapping ninja...
warning: A compatible version of re2c (>= 0.11.3) was not found; changes to src/*.in.cc will not affect your build.
./src/ninja.cc: In function 'int {anonymous}::GuessParallelism()':
./src/ninja.cc:248:9: error: redeclaration of 'int j'
  248 |   int   j = 0;
      |         ^
./src/ninja.cc:243:9: note: 'int j' previously declared here
  243 |   int   j = 0;
      |         ^
./src/ninja.cc:249:9: error: redeclaration of 'char* jobs'
  249 |   char* jobs = getenv( "NINJAJOBS" );
      |         ^~~~
./src/ninja.cc:244:9: note: 'char* jobs' previously declared here
  244 |   char* jobs = getenv( "NINJAJOBS" );
      |         ^~~~
./src/ninja.cc: In constructor '{anonymous}::DeferGuessParallelism::DeferGuessParallelism(BuildConfig*)':
./src/ninja.cc:1410:16: warning: '{anonymous}::DeferGuessParallelism::config' will be initialized after [-Wreorder]
 1410 |   BuildConfig* config;
      |                ^~~~~~
./src/ninja.cc:1409:8: warning:   'bool {anonymous}::DeferGuessParallelism::needGuess' [-Wreorder]
 1409 |   bool needGuess;
      |        ^~~~~~~~~
./src/ninja.cc:1412:3: warning:   when initialized here [-Wreorder]
 1412 |   DeferGuessParallelism(BuildConfig* config)
      |   ^~~~~~~~~~~~~~~~~~~~~
when running:  /bin/g++ -MMD -MT build/ninja.o -MF build/ninja.o.d -g -Wall -Wextra -Wno-deprecated -Wno-missing-field-initializers -Wno-unused-parameter -fno-rtti -fno-exceptions -fvisibility=hidden -pipe '-DNINJA_PYTHON="python3"' -O2 -DNDEBUG -fdiagnostics-color -DUSE_PPOLL -DNINJA_HAVE_BROWSE -I. -c ./src/ninja.cc -o build/ninja.o
Traceback (most recent call last):
  File "/src/ninja-1.11.1/configure.py", line 553, in <module>
    objs = cxx('ninja', variables=cxxvariables)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/ninja-1.11.1/configure.py", line 287, in cxx
    return n.build(built(name + objext), 'cxx', src(name + '.cc'), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/ninja-1.11.1/configure.py", line 169, in build
    self._run_command(self._expand(cmd, local_vars))
  File "/src/ninja-1.11.1/configure.py", line 194, in _run_command
    subprocess.check_call(cmdline, shell=True)
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/bin/g++ -MMD -MT build/ninja.o -MF build/ninja.o.d -g -Wall -Wextra -Wno-deprecated -Wno-missing-field-initializers -Wno-unused-parameter -fno-rtti -fno-exceptions -fvisibility=hidden -pipe '-DNINJA_PYTHON="python3"' -O2 -DNDEBUG -fdiagnostics-color -DUSE_PPOLL -DNINJA_HAVE_BROWSE -I. -c ./src/ninja.cc -o build/ninja.o' returned non-zero exit status 1.
```

**Comment by digit-google** [comment]
This is puzzling because there is no statement that looks like `int  j = 0` (with any number of whitespace) in the src/ninja.cc of the 1.11.1 release. Are you sure you have not applied some incorrect patches on top of the official release?

**Comment by xry111** [comment]
Obviously the OP has entered the sed in the book twice.

Please do not report the issues building LFS directly to the upstream w/o a proper diagnostic yourself, nor a communication via #lfs-support or lfs-support mail list.  Such invalid issue reports annoys upstream maintainers and lowers the reputation of LFS team.
